### ISSUE TITLE
Yireo Training

### ISSUE THREAD

**Issue by gcampedelli** [yireo-training/vsf-yireo-theme#1]
By the way, do you have an online training for vuestorefront and Magento2? Well, I'm not based in Europe.

**Comment by jissereitsma** [comment]
Thanks for reaching out to us. The bug on the training site is now fixed. We do offer online on a demand training as well. Feel free to send us a mail via info@yireo.com for further details. Please note that this forum here was only meant to discuss the code of this specific repository, so if you have any questions on the VSF theme, please shoot. But otherwise I think this issue is better closed.

**Comment by gcampedelli** [comment]
Thanks for answer. I'm trying to install it in VPS but I get 502 gateway in Nginx.

**Comment by jissereitsma** [comment]
Do you mean that you are getting a 502 error specifically with this theme in place? Because Nginx would be part of the total of the Vue Storefront setup, while this theme is only written in Node and would only generate errors in a Node webserver (local or remote). If you issues with Vue Storefront itself, it would be best to contact all Vue Storefront developers via the regular support channels.

**Comment by gcampedelli** [comment]
Well, I've configured NGINX according to file they provided. And, yes, I get 502 but I couldn't find any useful help in VueStorefront repository, except for a Git Memory that faced exact same problem but no resolution =>  https://www.gitmemory.com/issue/cristian-g/vsf-odoo/27/507635681

**Comment by jissereitsma** [comment]
Ok, then this would be really an issue to post on the Vue Storefront Slack channels or other official channels, instead of here. I'll close this issue here.

As a hint, the 502 error most likely means that an error is logged somewhere in the Nginx logs, so it is worth checking that out.
